" notwendig & Basiskonfig {
set nocompatible
set backspace=indent,eol,start
filetype plugin on
set encoding=utf-8
set ffs=unix,dos,mac
" }

" Syntaxhighlighting & Farbe {
syntax enable
set background=dark
colorscheme default
set t_Co=16
" }

" Einrückung & Tabulator {
filetype indent on
set autoindent
set smartindent
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
" }

" Bedienung {
set number
set cursorline
set showmode
set showcmd
set ruler
set laststatus=2
set wrap
set title
set scrolloff=1
set sidescrolloff=1
set autoread
set autowrite       " Automatically save before commands like :next and :make
set wildmenu
set wildmode=longest:full,full
set wildignore+=tags,.*.un~,*.pyc
set lazyredraw
" }

" Suche {
set incsearch
set ignorecase
set smartcase
set hlsearch
" }

" Mappings {
:let mapleader = ','
nmap < [
nmap > ]
omap < [
omap > ]
xmap < [
xmap > ]
" }

" Plugins {
call plug#begin('~/.vim/plugged')
runtime plugins.vim
call plug#end()

runtime plugin-settings.vim
" }
