#!/bin/bash

if [[ -z "$LESSOPEN" ]]; then
    LESSOPEN='|"$HOME/.lessfilter" %s'
fi
export LESSOPEN

export PATH="$HOME/.linuxbrew/bin:$PATH"
export MANPATH="$HOME/.linuxbrew/share/man:$MANPATH"
export INFOPATH="$HOME/.linuxbrew/share/info:$INFOPATH"
