#!/bin/bash

source ~/.dotfiles/.dl/zshrc_grml
source ~/.zsh/aliases

export DISTRO_ID="$(grep "^ID=" /etc/os-release | cut -d'=' -f2)"

if [[ "$DISTRO_ID" == "debian" ]]; then
    source ~/.zsh/aliases_debian
elif [[ "$DISTRO_ID" == "opensuse" ]]; then
    source ~/.zsh/aliases_opensuse
fi

# Shell-Funktionen
source ~/.zsh/functions

export PATH="$HOME/.dotfiles/bin:$HOME/.local/bin:$PATH"

[[ -e ~/.sdkman/bin/sdkman-init.sh ]] && source ~/.sdkman/bin/sdkman-init.sh
source ~/.zsh/virtualenvwrapper.sh

setopt HIST_IGNORE_SPACE

# Only load Liquid Prompt in interactive shells, not from a script or from scp
[[ $- = *i* ]] && source ~/.zsh/liquidprompt/liquidprompt

source ~/.zsh/highlighting/zsh-syntax-highlighting.zsh
