#!/bin/bash

source ~/.dotfiles/dl/zshrc_grml
source ~/.zsh/aliases

# Shell-Funktionen
for func in ~/.zsh/functions/*; do
    source "$func"
done

export PATH="$HOME/.dotfiles/bin:$PATH"
[[ -e ~/.sdkman/bin/sdkman-init.sh ]] && source ~/.sdkman/bin/sdkman-init.sh
source ~/.zsh/highlighting/zsh-syntax-highlighting.zsh
