" Default settings {{{1
runtime defaults.vim
set nocompatible
set backspace=indent,eol,start
set encoding=utf-8
set ffs=unix,dos,mac

" Einrückung, Tabulator "
filetype plugin indent on
syntax on
set autoindent
set smartindent
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
silent! set breakindent
set formatoptions+=lor
set iskeyword-=_
set nrformats=
set lbr
set showbreak=**\ \

" Bedienung "
set number
set relativenumber
set cursorline
set showmode
set showcmd
set ruler
set laststatus=2
set wrap
set title
set scrolloff=7
set sidescrolloff=7
set sidescroll=1
set updatetime=250
set autoread
set autowrite       " Automatically save before commands like :next and :make
set wildmenu
set wildmode=longest:full,full
set wildignore+=tags,.*.un~,*.pyc
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png,*.ico,*.tif
set wildignore+=*.pdf,*.psd,*.xcf,*.dvi
set wildignore+=*.aux,*.lof,*.lot,*.fls,*.toc,*.fmt,*.fot,*.cb,*.cb2,.*.lb,*.out
set wildignore+=*.fdb_latexmk,*.synctex.gz
set wildignore+=node_modules/*,bower_components/*,site-packages/*
set lazyredraw
set splitright
set splitbelow
set hidden
set foldmethod=marker

" Suche "
set incsearch
set ignorecase
set smartcase
set nohlsearch
" }}}1
" Plugins {{{1
" automatically install vim-plug {{{
if empty(glob('~/.vim/autoload/plug.vim'))
    silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
                \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
" }}}
" Cond1 function {{{
function! Cond1(cond, ...)
    let opts = get(a:000, 0, {})
    return a:cond ? opts : extend(opts, { 'on': [], 'for': [] })
endfunction
" }}}

call plug#begin('~/.vim/.vimplug')

Plug 'tpope/vim-abolish'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-jdaddy'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rhubarb'
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-speeddating'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-vinegar'

Plug 'Quramy/vim-js-pretty-template'
Plug 'ajh17/VimCompletesMe'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'editorconfig/editorconfig-vim'
Plug 'isa/vim-matchit'
Plug 'junegunn/gv.vim'
Plug 'lervag/vimtex'
Plug 'mattn/emmet-vim'
Plug 'neomake/neomake'
Plug 'scrooloose/nerdcommenter'
Plug 'sheerun/vim-polyglot'
Plug 'sjl/gundo.vim'
Plug 'w0rp/ale'
Plug 'xero/securemodelines'

Plug 'NLKNguyen/papercolor-theme'

call plug#end()
" }}}1
" Mappings {{{1
let mapleader = 's'
let maplocalleader = ','

nnoremap <Leader>m :set so=999<CR>
nnoremap <Leader>M :set so=0<CR>

nnoremap <Leader>er :e $MYVIMRC<CR>
nnoremap <Leader>sr :source $MYVIMRC<CR>

nnoremap <Down> gj
nnoremap <C-j> gj
nnoremap <Up> gk
nnoremap <C-k> gk
inoremap ii <Esc>$a
inoremap jk <Esc>
nnoremap + :

" edit files in the same directory
cnoremap %% <C-R>=fnameescape(expand('%:h')).'/'<CR>
nmap <Leader>ew :e %%
nmap <Leader>es :sp %%
nmap <Leader>ev :vsp %%
nmap <Leader>et :tabe %%
" }}}
colorscheme PaperColor
set background=light
" Plugin settings {{{1
" ctrlp {{{
let g:ctrlp_show_hidden = 1
" }}}
" gutentags {{{
let g:gutentags_cache_dir = '~/.cache/tags'
let g:gutentags_modules = ['ctags', 'cscope']
" }}}
" emmet {{{
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
" }}}
" markdown {{{
let g:markdown_fenced_languages = ['html', 'python', 'bash=sh', 'json']
let g:markdown_syntax_conceal = 0
let g:markdown_minlines = 100
" }}}
" nerdcommenter {{{
let g:NERDSpaceDelims = 1
" }}}
" rainbow {{{
let g:rainbow_active = 1
" }}}
" vimtex {{{
let g:tex_flavor = 'latex'
let g:polyglot_disabled = ['latex']
let g:vimtex_format_enabled = 1

let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_view_general_options = '--unique file:@pdf\#src:@line@tex'
let g:vimtex_view_general_options_latexmk = '--unique'
"}}}
" }}}1
