runtime defaults.vim
set nocompatible
set backspace=indent,eol,start
set encoding=utf-8
set ffs=unix,dos,mac

" Einrückung, Tabulator "
filetype plugin indent on
syntax on
set autoindent
set smartindent
set expandtab
set shiftwidth=4
set tabstop=4
set softtabstop=4
silent! set breakindent
set formatoptions+=lor
set iskeyword-=_
set nrformats=
set lbr
set showbreak=**\ \

" Bedienung "
set number
set relativenumber
set cursorline
set showmode
set showcmd
set ruler
set laststatus=2
set wrap
set title
set scrolloff=7
set sidescrolloff=7
set sidescroll=1
set updatetime=250
set autoread
set autowrite       " Automatically save before commands like :next and :make
set wildmenu
set wildmode=longest:full,full
set wildignore+=tags,.*.un~,*.pyc
set wildignore+=*.bmp,*.gif,*.ico,*.jpg,*.png,*.ico,*.tif
set wildignore+=*.pdf,*.psd,*.xcf
set wildignore+=node_modules/*,bower_components/*,site-packages/*
set lazyredraw
set splitright
set splitbelow
set hidden
set foldmethod=marker

" Suche "
set incsearch
set ignorecase
set smartcase
set nohlsearch

set background=light

" # Mappings {{{1
let mapleader = 's'
let maplocalleader = 's'

nmap <Leader>m :set so=999<CR>
nmap <Leader><Leader>m :set so=0<CR>

nmap <Leader>ev :e $MYVIMRC<CR>

nnoremap j gj
nnoremap k gk
inoremap ii <Esc>$a
inoremap jk <Esc>
nnoremap + :

augroup autosourcing
    autocmd!
    autocmd BufWritePost vimrc source %
augroup END

" edit files in the same directory
cnoremap %% <C-R>=fnameescape(expand('%:h')).'/'<CR>
map <Leader>ew :e %%
map <Leader>es :sp %%
map <Leader>ev :vsp %%
map <Leader>et :tabe %%
" }}}
