#!/bin/bash

#misc
alias grubupdate='sudo grub2-mkconfig -o /boot/grub2/grub.cfg && sudo grub2-install /dev/sda'

# server
alias cdwww='cd /srv/www'
alias dup='sudo zypper dup --no-allow-vendor-change'
alias ncctl='sudo sudo -u wwwrun php /srv/www/htdocs/nextcloud/occ'
alias ngx='sudo sudo -u nginx'
alias occtl='sudo sudo -u wwwrun php /srv/www/htdocs/owncloud/occ'
alias pg='sudo sudo -iu postgres psql'
alias update-atom='sudo rpm -U https://atom.io/download/rpm'
alias update-vscode='sudo rpm -U https://vscode-update.azurewebsites.net/latest/linux-rpm-x64/stable'
alias www='sudo sudo -u wwwrun'
alias zp='sudo zypper patch'
alias zup='sudo zypper up'
