#!/bin/bash

# misc
alias chmod='chmod --preserve-root'
alias chown='chown --preserve-root'
alias cnf='command-not-found'
alias dirs='dirs -v'
alias g='git'
alias ip4="curl --silent 'https://4.ifcfg.me'"
alias ip6="curl --silent 'https://6.ifcfg.me'"
alias l='ls -lhp --color=auto'
alias lskern="tput setaf 3; uname -r | cut -d '-' -f -2; tput sgr0; rpm -q kernel-default | cut -d '-' -f 3- | cut -d '.' -f -4"
alias newline="sed -i '$a\'"
alias nopg='PAGER='
alias szhrc='source ~/.zshrc'
alias trim="sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//'"

# desktop
alias ch='chromium'
alias fx='q firefox'
alias gitka='gitk --all'
alias gw='q gwenview'
alias kdb='q kdbg'
alias kt='q kate'
alias ok='q okular'
alias ssha='ssh-add ~/.ssh/id_rsa < /dev/null &'
alias vplay='q mpv --shuffle --loop 1 *'

# programming
alias gdba='gdb -q -ex run -ex bt -ex kill -ex quit --args'
alias gpp='g++ -Wall -Wextra -g'
alias gppp='g++ -O2 -g -fno-omit-frame-pointer -DNDEBUG -fno-inline-functions -fno-inline-functions-called-once -fno-optimize-sibling-calls'
alias java-loc='printf "Impl.: %s \nTest: %s \nTotal: %s \n" "$(wc -l src/main/**/*.java | tail -n1)" "$(wc -l src/test/**/*.java | tail -n1)" "$(wc -l **/*.java | tail -n1)"'
alias remake='make clean && make -j4'
alias sdkman-install="curl --silent 'https://get.sdkman.io' | bash"
alias sdkman-source='source ~/.sdkman/bin/sdkman-init.sh'
alias vlg='valgrind --track-origins=yes'
alias vlgl='valgrind --track-origins=yes --leak-check=full --show-leak-kinds=all'
alias yarng='yarn global --prefix ~/.local'
