#!/bin/bash

#misc
alias grubupdate='sudo grub2-mkconfig --output /boot/grub2/grub.cfg && sudo grub2-install /dev/sda'

# server
alias cdwww='cd /srv/www'
alias dup='sudo zypper dup --no-allow-vendor-change'
alias ncctl='sudo sudo --user wwwrun php /srv/www/htdocs/nextcloud/occ'
alias ngx='sudo sudo --user nginx'
alias occtl='sudo sudo --user wwwrun php /srv/www/htdocs/owncloud/occ'
alias pg='sudo sudo --login --user postgres psql'
alias update-atom='sudo rpm --upgrade https://atom.io/download/rpm'
alias update-vscode='sudo rpm --upgrade https://vscode-update.azurewebsites.net/latest/linux-rpm-x64/stable'
alias www='sudo sudo --user wwwrun'
alias zp='sudo zypper patch'
alias zsx='zypper search --details --match-exact --type package'
alias zup='sudo zypper up'
