#!/bin/bash

function gstb()
{
    if (( $# != 1 )); then
        return 1
    fi
    local cb
    cb="$(git currentbranch)"
    git checkout -q "$1"
    git status
    git checkout -q "$cb"
}

function gsdst()
{
    while IFS= read -r -d '' i; do
        cd "$i/.." || return
        printf "--------------------\n\n%s\n" "$PWD"
        git fetch
        git status --porcelain
        cd "$OLDPWD" || return
    done < <(find . -type d -name '.git')
}

function gradle-checkstyle()
{
    printf "Main: %3d\n" "$(./gradlew checkstyleMain --rerun-tasks 2>&1 | ack "ant:checkstyle" | wc -l)"
    printf "Test: %3d\n" "$(./gradlew checkstyleTest --rerun-tasks 2>&1 | ack "ant:checkstyle" | wc -l)"
}

function version_gt()
{
    [[ "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1" ]]
}
