#!/bin/bash

function adngx()
{
    set -u
    local wwwuser='nginx'
    for f in "$@"; do
        if [[ -f "$f" ]]; then
            chmod 0640 "$f"
        elif [[ -d "$f" ]]; then
            chmod 0750 "$f"
        fi
        chown root:"$wwwuser" "$f"
    done
}

function ems()
{
    if [[ $(pgrep -x emacs) == "" ]]; then
        emacs
    else
        emacsclient -c
    fi
}

function gstb()
{
    if (( $# != 1 )); then
        return 1
    fi
    local cb
    cb="$(git currentbranch)"
    git checkout -q "$1"
    git status
    git checkout -q "$cb"
}

function gsdst()
{
    while IFS= read -r -d '' i; do
        cd "$i/.." || return
        printf "--------------------\n\n%s\n" "$PWD"
        git fetch
        git status --porcelain
        cd "$OLDPWD" || return
    done < <(find . -type d -name '.git')
}

function gradle-checkstyle()
{
    printf "Main: %3d\n" "$(./gradlew checkstyleMain --rerun-tasks 2>&1 | ack "ant:checkstyle" | wc -l)"
    printf "Test: %3d\n" "$(./gradlew checkstyleTest --rerun-tasks 2>&1 | ack "ant:checkstyle" | wc -l)"
}

function moshp()
{
    mosh --ssh="ssh -p $1" "$2"
}

function mv-extension()
{
    set -u
    if (( $# != 2 )); then
        return 1
    fi
    for i in *.$1; do
        mv "$i" "${i%%.$1}.$2"
    done
}

function version_gt()
{
    [[ "$(echo "$@" | tr " " "\n" | sort -V | head -n 1)" != "$1" ]]
}

function q()
{
    if [[ -z "$*" ]]; then
        echo "missing argument"
        return 1
    fi
    ("$@" &> /dev/null &)
    return 0
}
